// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZlVXH3UE4yCmp7CnyuI0ykaxRm5cHegQ',
    appId: '1:391120125087:web:6b6dc5b8305ade672136aa',
    messagingSenderId: '391120125087',
    projectId: 'indonesia-bijak-605dc',
    authDomain: 'indonesia-bijak-605dc.firebaseapp.com',
    storageBucket: 'indonesia-bijak-605dc.appspot.com',
    measurementId: 'G-5Y7DW1PEJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdz_d-aAW6AjniRoWxEaaAbRYFwvRp6g',
    appId: '1:391120125087:android:7dd82eafad9645a92136aa',
    messagingSenderId: '391120125087',
    projectId: 'indonesia-bijak-605dc',
    storageBucket: 'indonesia-bijak-605dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSPKePg1MtlqQGDLFv6un7szAJeJKgps',
    appId: '1:391120125087:ios:4a7af3664f4d18d32136aa',
    messagingSenderId: '391120125087',
    projectId: 'indonesia-bijak-605dc',
    storageBucket: 'indonesia-bijak-605dc.appspot.com',
    iosBundleId: 'com.example.mobPrak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqSPKePg1MtlqQGDLFv6un7szAJeJKgps',
    appId: '1:391120125087:ios:d9cc478045e205fb2136aa',
    messagingSenderId: '391120125087',
    projectId: 'indonesia-bijak-605dc',
    storageBucket: 'indonesia-bijak-605dc.appspot.com',
    iosBundleId: 'com.example.mobPrak.RunnerTests',
  );
}
