// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA48O4ByVihjkoHIV82SjXE3qARqUS2J00',
    appId: '1:919396843244:web:a0224d210838d1faf2afc9',
    messagingSenderId: '919396843244',
    projectId: 'indonesia-bijak',
    authDomain: 'indonesia-bijak.firebaseapp.com',
    storageBucket: 'indonesia-bijak.appspot.com',
    measurementId: 'G-Y4Z4QCTE6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASlelEpTYVsFqzr_RwHSJWxFOHUndmObo',
    appId: '1:919396843244:android:61fb17c352b10a89f2afc9',
    messagingSenderId: '919396843244',
    projectId: 'indonesia-bijak',
    storageBucket: 'indonesia-bijak.appspot.com',
  );
}
